version: '3.8'

services:
  web:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - quantbuild-net

  api:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./storage:/app/storage  # optional: for uploaded blueprints or PDFs
    environment:
      - MONGO_URI=mongodb://mongo:27017/quantbuild
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - quantbuild-net

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - quantbuild-net

  ai-processor:
    build:
      context: ./ai_models
    ports:
      - "8000:8000"
    volumes:
      - ./ai_models:/app
    networks:
      - quantbuild-net

volumes:
  mongo-data:

networks:
  quantbuild-net:
    driver: bridge
