version: '3.8'

services:
  jtech-backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/jtech_ai
    depends_on:
      - mongo

  jtech-ai-model:
    build: ./ai_models
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: